language: go

go:
  - 1.13.x

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  - go test ./... -v -covermode=count -coverprofile=coverage.out
  - cat coverage.out | grep -v "stegify.go" > coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - golangci-lint run